public class DataType{
	public static void main(String[] args){
		//Integers type(byte,short,int,log)
		
		byte age =50;
		System.out.printf("Your age is %d%n",age);
		
		short quantity = 32000;
		System.out.printf("I bought %d quantity of bags of my business%n",quantity);
		
		int populationInNigeria = 100000000;
		System.out.printf("The total population In Nigeria is %d%n",populationInNigeria);
		
		long worldPopulation = 800000000;
		System.out.printf("The world population is %d%n",worldPopulation);
		
		//float-point type(float,double)
		float myBalance = 123455.856575F;
		System.out.printf("Your account balance is %f%n",myBalance);
		
		double cbnReserve = 5575857.737367363;
		System.out.printf("The CBN.balance is %5f%n",cbnReserve);
		
		//Boolean type(boolean)
		boolean isJavaFun = true;
		System.out.printf("Is Java a Fun Language ? %b%n",isJavaFun);
		
		//Character type(char)
		char alpha = '@';
		System.out.printf("My email is Progresshope22%cgmail.com",alpha);
	}
}
