public class PrintMethod{
	public static void main(String[] args){
		//using the print()
		System.out.print("\"Learning Java is Fun\"\na");
		System.out.print(" Hey, come and learn Java with me");
		
		//using the println()
		System.out.println();
		System.out.println("I want to tell you that Java is different from Javascript");
		System.out.println(" \t this is the indented line");
		
		//using the printf()
		System.out.printf(" My name is %s and I love %s. Good day everyone\n","Progress","Java");
		System .out.printf("I am %d years old%n",25);
		System.out.printf("i bought Java JDK with %f naira%n",150.345);
		System.out.printf("i bought Java JDK with %.2f naira%n",150.345);
		
		boolean isJavaFun = true;
		System .out.printf("is java fun? %b",isJavaFun);
		}
	
		
}